<a href="https://colab.research.google.com/github/dubba1212/AIML/blob/master/Assignment_8(04_06_2020).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**1**
[Reversing an Array] 
Write a NumPy program to reverse an array (first element becomes last). 


Original array:
[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37]


Reverse array:
[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12]


In [7]:
import numpy as np
a=np.arange(12,38)
print("orginal array:-",a)
a=list(a)
a.reverse()
print("Reverse array:-",a)

orginal array:- [12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]
Reverse array:- [37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12]


**2**
[Make Border 1] 
Write a NumPy program to create a 2d array with 1 on the border and 0 inside. 
Original array:
[[ 1. 1. 1. 1. 1.]
...................
[ 1. 1. 1. 1. 1.]]
1 on the border and 0 inside in the array


In [9]:
m=int(input("enter no of rows"))
n=int(input("enter no of columns"))
a=np.arange(m*n).reshape(m,n)
for i in range(m):
  for j in range(n):
    if(i==0 or i==m-1 or j==0 or j==n-1):
      a[i][j]=1
    else:
      a[i][j]=0
print(a)

enter no of rows4
enter no of columns4
[[1 1 1 1]
 [1 0 0 1]
 [1 0 0 1]
 [1 1 1 1]]


**3**
[Membership Test] 
Write a NumPy program to test whether each element of a 1-D array is also present in a second array.


In [10]:
import numpy as np
a1 = np.array([],dtype="int32")
a2 = np.array([],dtype="int32")
m=int(input("enter size of array 1:-"))
for i in range(0,m):
  a1 = np.append(a1,int(input("enter values:-")))
n=int(input("enter size of array 2:-"))
for j in range(0,n):
  a2 = np.append(a2,int(input()))
r=np.array([],dtype=bool)
for i in a1:
  if i in a2:
    r=np.append(r,True)
  else:
    r=np.append(r,False)
print(r)

enter size of array 1:-5
enter values:-0
enter values:-10
enter values:-20
enter values:-40
enter values:-60
enter size of array 2:-2
0
40
[ True False False  True False]


**4**
[Set Difference] 
Write a NumPy program to find the set difference of two arrays. The set difference will return the sorted, unique values in array1 that are not in array2.


In [12]:
import numpy as np
a1 = np.array([],dtype="int32")
a2 = np.array([],dtype="int32")
m=int(input("enter size of array 1:-"))
for i in range(0,m):
  a1 = np.append(a1,int(input("enter values:-")))
n=int(input("enter size of array 2:-"))
for j in range(0,n):
  a2 = np.append(a2,int(input("enter values:-")))
r=np.array([],dtype=bool)
for i in a1:
  if i not in a2:
   r=np.append(r,i)
print(r)

enter size of array 1:-6
enter values:-0
enter values:-10
enter values:-20
enter values:-40
enter values:-60
enter values:-80
enter size of array 2:-6
enter values:-10
enter values:-30
enter values:-40
enter values:-50
enter values:-70
enter values:-90
[ 0 20 60 80]


**5**
[Formation of Diagonal Matrix] 
Write a NumPy program to create a 2-D array whose diagonal equals [4, 5, 6, 8] and 0's elsewhere.


In [13]:
a1=np.array([4,5,6,8])
a2=np.arange(16).reshape(4,4)
k=0
for i in range(0,4):
  for j in range(0,4):
    if(i==j):
      a2[i][j]=a1[k]
      k+=1
    else:
      a2[i][j]=0
print(a2)

[[4 0 0 0]
 [0 5 0 0]
 [0 0 6 0]
 [0 0 0 8]]
