<a href="https://colab.research.google.com/github/dubba1212/AIML/blob/master/DAY_8(3_06_2020).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###Modules:
1. pre-defined modules
2. User-defined modules

In [0]:
import string
string.digits

'0123456789'

In [0]:
import string as s
s.digits

'0123456789'

In [0]:
from string import digits,punctuation
print(digits)
print(punctuation)

0123456789
!"#$%&'()*+,-./:;<=>?@[\]^_`{|}~


In [0]:
from string import *
print(digits)
print(punctuation)

0123456789
!"#$%&'()*+,-./:;<=>?@[\]^_`{|}~


In [0]:
list1=[1,2,3,4,5]
sum1=0
for i in list1:
  sum1=sum1+i
print(sum1)  

15


###user-defined

### create file
1. def add(x+y)
 
  return X+Y
2. def wish(name):
 
 print("good afternoon",name)

 3. result="True"

In [0]:

#import operation as o
#o.wish("dubba")
#o.result

###Built-in function
1. math
2. statistics 

In [0]:
import math

In [0]:
math.factorial(5)

120

In [0]:
#using math module find out area of circle
def area(r):
  a=math.pi*r*r
  print(a)
area(7)

153.93804002589985


In [0]:
import statistics as s
list1=list(range(0,21))
list1
print(list1)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]


In [0]:
print(s.mean(list1))

10


In [0]:
print(s.median(list1))

10


In [0]:
list2=[1,1,33,1,4,2,1,2]
print(s.mode(list2))

1


In [0]:
s.stdev(list2)

11.10903750491978

In [0]:
s.variance(list2)

123.41071428571429

###random:
1. randint()-->randint(start,stop)
2. random()-->0-1
3. choice()-->give random value
4. randrange()-->stop value is excluded,last value is not there
5. choices()-->gives multiple values

In [0]:
import random
print(random.randint(1,10))
print(random.randrange(1,10))
print(random.random())

4
4
0.08279903145849221


In [0]:
list1=[1,2,3,4,5,11,2,13]
print(random.choice(list1))
print(random.choices(list1,k=3))

2
[2, 4, 13]


###os modules
1. rename()-->rename a file
2. mkdir()--> make a directory
3. remove()-->remove a file
4. getcwd()-->get current working directory
5. listdir()--> it give u list of thing available in the directory
6. chdir()-->changing a directory

In [0]:
import os 
os.mkdir("sample")


In [0]:
os.getcwd()

'/content'

In [0]:
os.listdir()

['.config', 'sample', 'sample_data']

In [0]:
os.mkdir("123")

In [0]:
os.rmdir("123")

###numpy packages:
1. operations related numerics
2. computational

In [0]:
import numpy as np
list1=[1,2,3,4,5]
array= np.array(list1)
print(array)
type(array)

[1 2 3 4 5]


numpy.ndarray

In [0]:
list2=list(range(1,11))
list2

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [0]:
arr1=np.arange(1,11)
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

###Differences Between python list and Numpy Array
1. less memory
2. fast
3. convenient

In [0]:
import sys
size=1000
list1=list(range(size))
print(sys.getsizeof(list1[0])*size)
arr1 = np.arange(1000)
print(arr1.itemsize*arr1.size)

24000
8000


In [0]:
import time
size=2000
list1=list(range(size))
list2=list(range(size))
start=time.time()
result= [x+y for x,y in zip(list1,list2)]
print("Time is:-",time.time()-start)

arr=np.arange(size)
arr1=np.arange(size)
start=time.time()
result=arr+arr1
print("Time is:-",time.time()-start)

Time is:- 0.0010938644409179688
Time is:- 0.0001361370086669922


In [89]:
l1=[1,2,3,4,5]
l2=[10,11,12,13,14]
result =[x+y for x,y in zip(l1,l2)]
result

[11, 13, 15, 17, 19]

In [90]:
a1=np.array(l1)
a2=np.array(l2)
a1+a2

array([11, 13, 15, 17, 19])