<a href="https://colab.research.google.com/github/dubba1212/AIML/blob/master/DAY_10(5_06_2020).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from numpy import random
print(random.randint(1,100))#random integer in the given range
print(random.rand())#float number 0-1

86
0.055035941142152156


In [4]:
#creating n-dimensional array with random integer values
print(random.randint(100,size=(5)))
print(random.randint(100,size=(5,5)))
print(random.randint(100,size=(3,4,2)))

[76 90 43 28 68]
[[87 26 59 95 94]
 [92 20 43 18 93]
 [19 63 72 54 37]
 [15 94 11 50 64]
 [27 23 66 62 13]]
[[[19 22]
  [22 62]
  [42 97]
  [12 35]]

 [[35  5]
  [39 35]
  [69 15]
  [65 11]]

 [[12 22]
  [59 52]
  [87 46]
  [56 36]]]


In [5]:
#creating n-dimensional array with random floating-integer values
print(random.rand())
print(random.rand(3))

0.8976631382916358
[0.34698182 0.58072183 0.70899744]


In [6]:
a = random.randint(100,size=(3,2)).ravel()
a

array([11, 87, 76, 77, 91, 49])

In [7]:
#single element will be selected
random.choice(a)

77

In [8]:
#for generating an array with the given shape and elements from the given list
random.choice([1,2,3,4,5],size=(4,4))

array([[4, 2, 1, 3],
       [5, 5, 5, 1],
       [4, 2, 3, 4],
       [4, 3, 4, 1]])

###pandas:
1. data manipulation,analysis and cleaning
2. tabular data,unlabled 

###Creating a DataFrame
1. using 2 dictionaries
2. simple dictionary -->DataFrame
3. using series

In [10]:
import pandas as pd
import numpy as np
dict1 = {'a':1,'b':2,'c':3,'d':4,'e':5}
dict2 = {'a':11,'b':12,'c':13,'d':14,'e':15,'f':16}
data = {"First":dict1,"Second":dict2}
df = pd.DataFrame(data)
df 

First  Second
a    1.0      11
b    2.0      12
c    3.0      13
d    4.0      14
e    5.0      15
f    NaN      16

In [11]:
#simple dictionary --> DataFrame
d1 = {"name":["dubba","srikanth","reddy"],"address":["hyd","lic","adc"]}
df1 = pd.DataFrame(d1)
df1

name address
0     dubba     hyd
1  srikanth     lic
2     reddy     adc

In [15]:
#using series
s1 = pd.Series([1,2,3,4,5,6,7,8,9,10])
s2 = pd.Series([11,23,12,14,16,3,12,99,88,00])
s3 = pd.Series([11,22,33,44,55,66,77,88,99,111])
s4 = pd.Series(['a','s','d','f','g','h','j','k','l','d'])
data = {"col1":s1,"col2":s2,"col3":s3,"col4":s4}
df3 = pd.DataFrame(data)
df3

col1  col2  col3 col4
0     1    11    11    a
1     2    23    22    s
2     3    12    33    d
3     4    14    44    f
4     5    16    55    g
5     6     3    66    h
6     7    12    77    j
7     8    99    88    k
8     9    88    99    l
9    10     0   111    d

###selecting the data from the DataFrame
1. loc-->row and column values
2. iloc-->row and column  index values

In [16]:
df3["col2"]

0    11
1    23
2    12
3    14
4    16
5     3
6    12
7    99
8    88
9     0
Name: col2, dtype: int64

In [18]:
df3[["col1","col4"]]

col1 col4
0     1    a
1     2    s
2     3    d
3     4    f
4     5    g
5     6    h
6     7    j
7     8    k
8     9    l
9    10    d

In [24]:
df3.loc[:,["col1","col4"]]

col1 col4
0     1    a
1     2    s
2     3    d
3     4    f
4     5    g
5     6    h
6     7    j
7     8    k
8     9    l
9    10    d

In [23]:
#it accepts row and column,for single column
df3.loc[0:5,["col1","col4"]]

col1 col4
0     1    a
1     2    s
2     3    d
3     4    f
4     5    g
5     6    h

In [25]:
df3.iloc[:,0]

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
Name: col1, dtype: int64

In [26]:
df3.iloc[0:4,0:1]

col1
0     1
1     2
2     3
3     4

###Retrieving the information of DataFrame


In [27]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   col1    10 non-null     int64 
 1   col2    10 non-null     int64 
 2   col3    10 non-null     int64 
 3   col4    10 non-null     object
dtypes: int64(3), object(1)
memory usage: 448.0+ bytes


In [28]:
df3.shape

(10, 4)

In [29]:
df3.columns

Index(['col1', 'col2', 'col3', 'col4'], dtype='object')

In [30]:
df3.index

RangeIndex(start=0, stop=10, step=1)

###viewing data from Dataframe:
1. head()
2. tail()
3. sample()

In [31]:
#First 5 rows
df3.head()

col1  col2  col3 col4
0     1    11    11    a
1     2    23    22    s
2     3    12    33    d
3     4    14    44    f
4     5    16    55    g

In [32]:
df3.head(3)

col1  col2  col3 col4
0     1    11    11    a
1     2    23    22    s
2     3    12    33    d

In [33]:
df3.tail()

col1  col2  col3 col4
5     6     3    66    h
6     7    12    77    j
7     8    99    88    k
8     9    88    99    l
9    10     0   111    d

In [34]:
#last two rows
df3.tail(2)

col1  col2  col3 col4
8     9    88    99    l
9    10     0   111    d

In [35]:
df3.sample()

col1  col2  col3 col4
4     5    16    55    g

In [36]:
df3.sample(2)

col1  col2  col3 col4
3     4    14    44    f
4     5    16    55    g

In [37]:
df3.describe()

col1       col2        col3
count  10.00000  10.000000   10.000000
mean    5.50000  27.800000   60.600000
std     3.02765  35.301243   33.470385
min     1.00000   0.000000   11.000000
25%     3.25000  11.250000   35.750000
50%     5.50000  13.000000   60.500000
75%     7.75000  21.250000   85.250000
max    10.00000  99.000000  111.000000

In [39]:
df3=df3.rename(columns={"col1":"First",
                    "col2":"Second",
                    "col3":"Third",
                    "col4":"Forth"})
df3

First  Second  Third Forth
0      1      11     11     a
1      2      23     22     s
2      3      12     33     d
3      4      14     44     f
4      5      16     55     g
5      6       3     66     h
6      7      12     77     j
7      8      99     88     k
8      9      88     99     l
9     10       0    111     d