<a href="https://colab.research.google.com/github/dubba1212/AIML/blob/master/DAY_20(17_06_2020).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###Preprocessing of the Data
steps involved in data pre-processing
1. importing libraries
2. importing the dataset
3. missing values
4. categorical data
5. splitting data
6. feature scaling

In [1]:
import pandas as pd 
import numpy as np
import sklearn

In [5]:
data = pd.read_csv("https://raw.githubusercontent.com/Mounika-Kajjam/Datasets/master/homeprices.csv")
data

town  area   price
0   monroe township  2600  550000
1   monroe township  3000  565000
2   monroe township  3200  610000
3   monroe township  3600  680000
4   monroe township  4000  725000
5      west windsor  2600  585000
6      west windsor  2800  615000
7      west windsor  3300  650000
8      west windsor  3600  710000
9       robinsville  2600  575000
10      robinsville  2900  600000
11      robinsville  3100  620000
12      robinsville  3600  695000

###Dummy variables using scikit-learn library
- LabelEncoder
- OneHolEncoder

LabelEncoder-->we are creati ng dummy variables

-- class present in sklearn
library

In [2]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [6]:
price_data = data.copy()
price_data

town  area   price
0   monroe township  2600  550000
1   monroe township  3000  565000
2   monroe township  3200  610000
3   monroe township  3600  680000
4   monroe township  4000  725000
5      west windsor  2600  585000
6      west windsor  2800  615000
7      west windsor  3300  650000
8      west windsor  3600  710000
9       robinsville  2600  575000
10      robinsville  2900  600000
11      robinsville  3100  620000
12      robinsville  3600  695000

In [7]:
price_data.town = le.fit_transform(data.town)
price_data

town  area   price
0      0  2600  550000
1      0  3000  565000
2      0  3200  610000
3      0  3600  680000
4      0  4000  725000
5      2  2600  585000
6      2  2800  615000
7      2  3300  650000
8      2  3600  710000
9      1  2600  575000
10     1  2900  600000
11     1  3100  620000
12     1  3600  695000

###OneHotEncoder-->similar to pd.get_dummies
-->import the oneholderencoder class
-->create an object for the class
-->columnTrasformer-->insider this columntransfrom, we will pass th9is OneHolderEncoder
-->transformer argument, it will accept a list of tuples values

In [8]:
##Importing Librearies
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

In [16]:
#Insider the columntranformer, we have to pass the
column_transformer = ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[0])],remainder='passthrough')

In [ ]:
#objectname.fit_transformer(data)

In [19]:
data = column_transformer.fit_transform(data)
data

array([[1.00e+00, 0.00e+00, 0.00e+00, 2.60e+03, 5.50e+05],
       [1.00e+00, 0.00e+00, 0.00e+00, 3.00e+03, 5.65e+05],
       [1.00e+00, 0.00e+00, 0.00e+00, 3.20e+03, 6.10e+05],
       [1.00e+00, 0.00e+00, 0.00e+00, 3.60e+03, 6.80e+05],
       [1.00e+00, 0.00e+00, 0.00e+00, 4.00e+03, 7.25e+05],
       [0.00e+00, 0.00e+00, 1.00e+00, 2.60e+03, 5.85e+05],
       [0.00e+00, 0.00e+00, 1.00e+00, 2.80e+03, 6.15e+05],
       [0.00e+00, 0.00e+00, 1.00e+00, 3.30e+03, 6.50e+05],
       [0.00e+00, 0.00e+00, 1.00e+00, 3.60e+03, 7.10e+05],
       [0.00e+00, 1.00e+00, 0.00e+00, 2.60e+03, 5.75e+05],
       [0.00e+00, 1.00e+00, 0.00e+00, 2.90e+03, 6.00e+05],
       [0.00e+00, 1.00e+00, 0.00e+00, 3.10e+03, 6.20e+05],
       [0.00e+00, 1.00e+00, 0.00e+00, 3.60e+03, 6.95e+05]])

In [20]:
X = pd.DataFrame(data)
X

0    1    2       3         4
0   1.0  0.0  0.0  2600.0  550000.0
1   1.0  0.0  0.0  3000.0  565000.0
2   1.0  0.0  0.0  3200.0  610000.0
3   1.0  0.0  0.0  3600.0  680000.0
4   1.0  0.0  0.0  4000.0  725000.0
5   0.0  0.0  1.0  2600.0  585000.0
6   0.0  0.0  1.0  2800.0  615000.0
7   0.0  0.0  1.0  3300.0  650000.0
8   0.0  0.0  1.0  3600.0  710000.0
9   0.0  1.0  0.0  2600.0  575000.0
10  0.0  1.0  0.0  2900.0  600000.0
11  0.0  1.0  0.0  3100.0  620000.0
12  0.0  1.0  0.0  3600.0  695000.0

In [ ]:
#importing the classes
##creating the objects
##to apply the object to the dataframe(columns), we are using fit_transform-->with help of fit_transform
##LabelEncoder is used only when we have to classes

###Splitting the Dataset

In [21]:
price = pd.read_csv("https://raw.githubusercontent.com/Mounika-Kajjam/Datasets/master/homeprices.csv")

In [22]:
#town and area -->input column
X = price.iloc[:,0:2] #preparing input variable/column
X

town  area
0   monroe township  2600
1   monroe township  3000
2   monroe township  3200
3   monroe township  3600
4   monroe township  4000
5      west windsor  2600
6      west windsor  2800
7      west windsor  3300
8      west windsor  3600
9       robinsville  2600
10      robinsville  2900
11      robinsville  3100
12      robinsville  3600

In [23]:
#preparing the output variable
y = price.price
y

0     550000
1     565000
2     610000
3     680000
4     725000
5     585000
6     615000
7     650000
8     710000
9     575000
10    600000
11    620000
12    695000
Name: price, dtype: int64

In [ ]:
seperate the Input training and testing
seperate the Output training and testing

In [24]:
from sklearn.model_selection import train_test_split
X_train, X_test ,y_train ,y_test = train_test_split(X,y,test_size=0.2)

In [25]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(10, 2)
(3, 2)
(10,)
(3,)


In [26]:
X_train

town  area
7      west windsor  3300
4   monroe township  4000
12      robinsville  3600
6      west windsor  2800
9       robinsville  2600
3   monroe township  3600
2   monroe township  3200
5      west windsor  2600
10      robinsville  2900
8      west windsor  3600

In [27]:
sample = pd.DataFrame({'W.E':[2,4,5,6,7,8],'Age':[28,25,32,45,33,32],
                       'salary':[300000,400000,500000,600000,700000,800000,],
                       'Distance':[10,11,22,33,14,15],
                       'Expected salary':[400000,500000,600000,700000,800000,900000]})
sample

W.E  Age  salary  Distance  Expected salary
0    2   28  300000        10           400000
1    4   25  400000        11           500000
2    5   32  500000        22           600000
3    6   45  600000        33           700000
4    7   33  700000        14           800000
5    8   32  800000        15           900000

-->most the machine learning  algorithms, we use distance based formulas

In [28]:
from sklearn.preprocessing import scale
scaled_data = scale(sample)
scaled_data

array([[-1.69030851, -0.72134777, -1.46385011, -0.94553674, -1.46385011],
       [-0.6761234 , -1.20224629, -0.87831007, -0.81946518, -0.87831007],
       [-0.16903085, -0.08014975, -0.29277002,  0.56732205, -0.29277002],
       [ 0.3380617 ,  2.00374382,  0.29277002,  1.95410927,  0.29277002],
       [ 0.84515425,  0.08014975,  0.87831007, -0.44125048,  0.87831007],
       [ 1.35224681, -0.08014975,  1.46385011, -0.31517891,  1.46385011]])

In [29]:
scaled_data = pd.DataFrame(scaled_data)
scaled_data

0         1        2         3        4
0 -1.690309 -0.721348 -1.46385 -0.945537 -1.46385
1 -0.676123 -1.202246 -0.87831 -0.819465 -0.87831
2 -0.169031 -0.080150 -0.29277  0.567322 -0.29277
3  0.338062  2.003744  0.29277  1.954109  0.29277
4  0.845154  0.080150  0.87831 -0.441250  0.87831
5  1.352247 -0.080150  1.46385 -0.315179  1.46385

In [31]:
standard_data=sample.copy()#creating copy of original data set
standard_data

array([[-1.69030851, -0.72134777, -1.46385011, -0.94553674, -1.46385011],
       [-0.6761234 , -1.20224629, -0.87831007, -0.81946518, -0.87831007],
       [-0.16903085, -0.08014975, -0.29277002,  0.56732205, -0.29277002],
       [ 0.3380617 ,  2.00374382,  0.29277002,  1.95410927,  0.29277002],
       [ 0.84515425,  0.08014975,  0.87831007, -0.44125048,  0.87831007],
       [ 1.35224681, -0.08014975,  1.46385011, -0.31517891,  1.46385011]])

In [32]:
#using standardscaler
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
sample=sc.fit_transform(sample)
sample

array([[-1.69030851, -0.72134777, -1.46385011, -0.94553674, -1.46385011],
       [-0.6761234 , -1.20224629, -0.87831007, -0.81946518, -0.87831007],
       [-0.16903085, -0.08014975, -0.29277002,  0.56732205, -0.29277002],
       [ 0.3380617 ,  2.00374382,  0.29277002,  1.95410927,  0.29277002],
       [ 0.84515425,  0.08014975,  0.87831007, -0.44125048,  0.87831007],
       [ 1.35224681, -0.08014975,  1.46385011, -0.31517891,  1.46385011]])

In [33]:
sample = pd.DataFrame(sample)
sample

0         1        2         3        4
0 -1.690309 -0.721348 -1.46385 -0.945537 -1.46385
1 -0.676123 -1.202246 -0.87831 -0.819465 -0.87831
2 -0.169031 -0.080150 -0.29277  0.567322 -0.29277
3  0.338062  2.003744  0.29277  1.954109  0.29277
4  0.845154  0.080150  0.87831 -0.441250  0.87831
5  1.352247 -0.080150  1.46385 -0.315179  1.46385

In [35]:
##MinMaxScaler
from sklearn.preprocessing import MinMaxScaler
ms = MinMaxScaler()
ms.fit(standard_data)
standard_data = ms.transform(standard_data)
standard_data

array([[0.        , 0.15      , 0.        , 0.        , 0.        ],
       [0.33333333, 0.        , 0.2       , 0.04347826, 0.2       ],
       [0.5       , 0.35      , 0.4       , 0.52173913, 0.4       ],
       [0.66666667, 1.        , 0.6       , 1.        , 0.6       ],
       [0.83333333, 0.4       , 0.8       , 0.17391304, 0.8       ],
       [1.        , 0.35      , 1.        , 0.2173913 , 1.        ]])

In [36]:
standard_data = pd.DataFrame(standard_data)
standard_data

0     1    2         3    4
0  0.000000  0.15  0.0  0.000000  0.0
1  0.333333  0.00  0.2  0.043478  0.2
2  0.500000  0.35  0.4  0.521739  0.4
3  0.666667  1.00  0.6  1.000000  0.6
4  0.833333  0.40  0.8  0.173913  0.8
5  1.000000  0.35  1.0  0.217391  1.0

In [43]:
def fun(x):
  x[0] = 5

  return x
g = [10,11,12]

print(fun(g),g)

[5, 11, 12] [5, 11, 12]
