<a href="https://colab.research.google.com/github/dubba1212/AIML/blob/master/DAY_9(4_06_2020).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###Numpy package:
1. Numerical data
2. computations on numerics


In [0]:
import numpy as np

###Difference Between numpy array and list:
1. less memory
2. fast
3. convenient

In [3]:
#1-dimensional array
a = np.array([1,2,3,4,5])
print(a.ndim)

1


In [4]:
#2-dimensional array
a1 = np.array([[1,2,3,],[4,5,6],[7,8,9]])
a1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
a1.shape

(3, 3)

In [7]:
a2 = np.array([[1,2,3,],[4,5,6],[7,8,9],[10,11,12]])
print(a2.shape[0])#rows
print(a2.shape[1])#columns

4
3


In [0]:
#getting elements from a user
a3 = np.array([],dtype="int32")

In [10]:
#single element
a3 = np.append(a3,int(input()))
a3

12


array([12])

In [12]:
a3 = np.append(a3,[13,14,15,16])
a3

array([12, 13, 14, 15, 16])

###slicing:


In [13]:
print(a3[2])

14


In [16]:
print(a2[1,2])

6


In [19]:
print(a2[2:,:])

[[ 7  8  9]
 [10 11 12]]


In [20]:
print(a2[2:,0:2])

[[ 7  8]
 [10 11]]


In [21]:
a2

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [22]:
print(a2[0:,0:2])

[[ 1  2]
 [ 4  5]
 [ 7  8]
 [10 11]]


In [23]:
print(a2[0::2,:])

[[1 2 3]
 [7 8 9]]


###iterate through array:

In [24]:
for row in a2:
  print(row)

[1 2 3]
[4 5 6]
[7 8 9]
[10 11 12]


In [26]:
for ele in a2.flat:
  print(ele,end=" ")

1 2 3 4 5 6 7 8 9 10 11 12 

In [27]:
np.array(a2.flat)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

###indexing with boolean array

In [30]:
a4 = np.arange(1,21).reshape(5,4)
a4

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [33]:
result = (a4 % 2 ==0)
result

array([[False,  True, False,  True],
       [False,  True, False,  True],
       [False,  True, False,  True],
       [False,  True, False,  True],
       [False,  True, False,  True]])

In [35]:
a4[result]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [0]:
a5 = np.arange(1,10).reshape(3,3)
a6 = np.arange(11,20).reshape(3,3)


In [39]:
a5

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [40]:
a6

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [42]:
print(np.vstack((a5,a6)))#vertical stacking

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [11 12 13]
 [14 15 16]
 [17 18 19]]


In [43]:
print(np.hstack((a5,a6)))#horizontal stacking

[[ 1  2  3 11 12 13]
 [ 4  5  6 14 15 16]
 [ 7  8  9 17 18 19]]


###Attributes:
1. size
2. itemsize
3. dtype-->change data type
4. ndim-->which type of your array is
5. shape

In [44]:
arr = np.arange(1,11).reshape(2,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [45]:
print(arr.size)
print(arr.itemsize)
print(arr.dtype)
print(arr.ndim)
print(arr.shape)

10
8
int64
2
(2, 5)


###Functions:
1. zeros()
2. ones()
3. full()
4. eye()
5. linspace()
6. arange()
7. reshape()
8. ravel()

In [54]:
z= np.zeros((2,3) , dtype ="int32")
print(z)

[[0 0 0]
 [0 0 0]]


In [53]:
o = np.ones((3,3), dtype="int32")
print(o)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [52]:
f = np.full((2,2),"dubba")
print(f)

[['dubba' 'dubba']
 ['dubba' 'dubba']]


In [60]:
#eye()
e = np.eye(3,dtype="int32")
print(e)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [62]:
#liinspace()-->linear spacing elements
l=np.linspace(1,10,5)
l

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [65]:
a= np.arange(1,13,2)
a

array([ 1,  3,  5,  7,  9, 11])

In [66]:
#ravel()-->flatten your array elements
print(np.array(a.flat))
print(a.ravel())

[ 1  3  5  7  9 11]
[ 1  3  5  7  9 11]


###Function:
1. min()
2. max()
3. sum()
4. sqrt()
5. mean()
6. median()
7. std()


In [74]:
s=a.reshape(2,3)
s

array([[ 1,  3,  5],
       [ 7,  9, 11]])

In [67]:
print(a.min())
print(a.max())

1
11


In [72]:
print(s.sum())#sum of all elements
print(s.sum(axis=1))#sum of row elements
print(s.sum(axis=0))#sum of column elements

10
[2 2 2 2 2]
[0 5 0 5]


In [75]:
np.sqrt(s)

array([[1.        , 1.73205081, 2.23606798],
       [2.64575131, 3.        , 3.31662479]])

In [76]:
np.mean(s)

6.0

In [77]:
np.median(s)

6.0

In [78]:
np.std(s)

3.415650255319866

###mathematical operations:+,-,*,/,%

In [95]:
arr=np.arange(1,10).reshape(3,3)
arr1=np.arange(11,20).reshape(3,3)
print(arr,end=" ")

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

In [96]:
arr1

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [84]:
print(arr+arr1)

[[12 14 16]
 [18 20 22]
 [24 26 28]]


In [85]:
print(arr-arr1)

[[-10 -10 -10]
 [-10 -10 -10]
 [-10 -10 -10]]


In [86]:
print(arr*arr1)

[[ 11  24  39]
 [ 56  75  96]
 [119 144 171]]


In [87]:
print(arr/arr1)

[[0.09090909 0.16666667 0.23076923]
 [0.28571429 0.33333333 0.375     ]
 [0.41176471 0.44444444 0.47368421]]


In [88]:
print(arr%arr1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


###dot()-->matrix multiplication
###arr1 = mXn
###arr2 = nX1


In [97]:
s1 = np.arange(1,10).reshape(3,3)
s2 = np.arange(11,20).reshape(3,3)
s1.dot(s2)

array([[ 90,  96, 102],
       [216, 231, 246],
       [342, 366, 390]])

In [98]:
s1


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [100]:
#Transpose of an array
s1.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

###Apply user defind function to a array

In [101]:
list1 = list(range(1,20))
list1

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [106]:
a=np.array(list1)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [0]:
#1/(1+)-->x/(x+1)
result = [x/(x+1) for x in list1]
result

In [108]:
f = np.vectorize(lambda x:x/(x+1))
f(a)

array([0.5       , 0.66666667, 0.75      , 0.8       , 0.83333333,
       0.85714286, 0.875     , 0.88888889, 0.9       , 0.90909091,
       0.91666667, 0.92307692, 0.92857143, 0.93333333, 0.9375    ,
       0.94117647, 0.94444444, 0.94736842, 0.95      ])